### ISSUE TITLE
CLI Vendorization

### ISSUE THREAD

**Issue by akalipetis** [platformsh/cli#79]
We need to introduce Vendor-support for the CLI so that we can distribute the binary CLI to white-label vendors. For this, we'll need the following things:

```[tasklist]
### Tasks
- [ ] https://github.com/platformsh/cli/issues/80
- [ ] https://github.com/platformsh/platformify/issues/120
- [ ] https://github.com/platformsh/cli/issues/81
```
